spring:
  application:
    name: TODO
  profiles:
    active: ${SPRING_PROFILE:local}
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    show-sql: false
    hibernate:
      jdbc.fetch_size: 40
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: ${SERVER_PORT:11080}

app:
  #jwtSecret: wyZEWblplLZ2XzB27iNodoXz7JOPGHs8
  #jwtExpirationMs: 900000 # 15 minutes
  #jwtRefreshExpirationMs: 86400000 # 1 day
  #description: TODO
  #version: 1.0


